import type { Metadata } from 'next'

import { Kumbh_Sans } from 'next/font/google'

import './globals.css'

import Providers from '@/components/providers/provider'
import NavBar from '@/components/navigation/navBar'

const kumbhSans = Kumbh_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={kumbhSans.className}>
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
